### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by CathyWilms** [TaylorHo/dnd-beyond-kit#4]
[de-de.json](https://github.com/user-attachments/files/16061609/de-de.json)
Have a german Translation. Dont know hot to add

**Comment by CathyWilms** [comment]
You are allowed to just add it. I dont know github at all.

**Comment by TaylorHo** [comment]
Hey @CathyWilms, thank you for the contribution ❤️
I will add it, no problems, thank you again 😄
