### ISSUE TITLE
Feature: Mobile Support

### ISSUE THREAD

**Issue by TaylorHo** [TaylorHo/dnd-beyond-kit#8]
The extension is working great in Desktop-sized environments (its main purpose). But if we decrease the width of the page, it will not translate the content (it's kinda boring if we want to split the screen between two different tools.

So, this issue is to discuss and plan a way of extending the translation support for smaller screens, allowing possibly to make the extension also available for mobile devices (such as through the Firefox Addons store and for WebView-based browsers for Android.

**Comment by TaylorHo** [comment]
@mlynarp want to help here? When and if you are available?

**Comment by mlynarp** [comment]
This would be great even though for me desktop is primary choice. On tablet and mobile phone they have dedicated app which is imho not translatable but its better usable then web. One idea can be to run the translation engine on the whole page and do not select areas, performance seems to be fine so it should work fine.

My free time is highly limited to just evening times (European time) when kids go to bed.

**Comment by TaylorHo** [comment]
Yeah, it's definitely not a "main feature". I'll keep this issue open just to remember that this can be implemented in the future ;)

Again, thanks for all the help around this extension =D

**Comment by TaylorHo** [comment]
The last commit ([8a31968](https://github.com/TaylorHo/dnd-beyond-kit/commit/8a319683065960308fa8c389cb2daacfe39dd89a)) implements Mobile support 🎉 

@mlynarp These latest changes also implement a different way of translating things, with all translations placed in "first-level" in the JSON files. I have replicated the PT-BR translations for other languages, but as I do not know Czech, can you please revise the translations when you have some free time? Czech non-revised translations are placed in lines [273-405](https://github.com/TaylorHo/dnd-beyond-kit/blob/main/translations/cs-cz.json#L273).

**Comment by mlynarp** [comment]
![image](https://github.com/user-attachments/assets/81d885f7-fdea-4799-8c8b-f3000052e6a3)
This is what I got after merge

**Comment by mlynarp** [comment]
Just a question, what was the reason to do flat translation? Its fine but just sometimes I am missing context like to word prone.

**Comment by mlynarp** [comment]
Good thing is that VS Code will mark the json string as duplicated if I insert new key so from that perspective its better to avoid duplication but still little bit missing the context :-)

**Comment by TaylorHo** [comment]
It was flattened for some reasons:

- VS Code showing us the duplications;
- A better way to compare different languages' translations (I'm working on a script to do these comparisons);
- It's simpler to process for the JS script, I've made some tests and the computational workload is minimized this way;
- The `translations.js` file becomes smaller, since it translates more areas, instead of focusing on only one per time (fewer repetitions in the code);
- Finally, when we resize the screen for mobile size, the translations are also applied.

I'm also working on a script to extract the untranslated strings from D&D Beyond, making it easier for us to translate. A flattened version would be easier to do since it reduces the computational workload to make this analysis.

**Comment by TaylorHo** [comment]
> ![image](https://private-user-images.githubusercontent.com/150273236/376021696-81d885f7-fdea-4799-8c8b-f3000052e6a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDkzMzgsIm5iZiI6MTcyODkwOTAzOCwicGF0aCI6Ii8xNTAyNzMyMzYvMzc2MDIxNjk2LTgxZDg4NWY3LWZkZWEtNDc5OS04YzhiLWYzMDAwMDUyZTZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMjMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjI4YTM4MGQ4M2I4N2IyMGI5ZmM1NzViMWRiOGE4ZDhjMGY3YjUzZDdhZTI0ZDQ3Y2FkYjBjOWUxYjY4YjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TjMwtjBfGhiCWIzJcVDPJwArU93YazUnDdyZUCO0q1Q)
> This is what I got after merge in Chrome

Yeah, the warning is due to the Firefox mutual support, so with the same `manifest.json` we can publish the extension to the Chrome web store and also to the Firefox Add-ons store.
